CREATE DATABASE IF NOT EXISTS cloudguard;
USE cloudguard;

CREATE TABLE IF NOT EXISTS ec2_instances (
    id INT AUTO_INCREMENT PRIMARY KEY,
    instance_id VARCHAR(255) NOT NULL,
    instance_type VARCHAR(255) NOT NULL,
    state VARCHAR(50) NOT NULL,
    cpu_utilization FLOAT DEFAULT 0.0,
    uptime_hours FLOAT DEFAULT 0.0,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS s3_buckets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    bucket_name VARCHAR(255) NOT NULL,
    size_mb FLOAT DEFAULT 0.0,
    days_since_last_access INT DEFAULT 0,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
